In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
x_ones = torch.ones_like(x_data)
x_ones

tensor([[1, 1],
        [1, 1]])

In [5]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"x_rand: \n{x_rand}\n")

x_rand: 
tensor([[0.2091, 0.1503],
        [0.2833, 0.3958]])



In [8]:
shape = (2, 3, )
t_rand = torch.rand(shape)
t_rand

tensor([[0.9716, 0.5806, 0.4223],
        [0.9992, 0.0204, 0.7304]])

In [9]:
t_ones = torch.ones(shape)
t_ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
t_zeros = torch.zeros(shape)
t_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
x_rand.device

device(type='cpu')

In [12]:
torch.cuda.is_available()

False

In [18]:
x_data[..., -1]

tensor([2, 4])

In [24]:
torch.cat([x_data, x_data], dim=1)

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4]])

In [25]:
x_data.T

tensor([[1, 3],
        [2, 4]])

In [26]:
x_data @ x_data.T

tensor([[ 5, 11],
        [11, 25]])

In [27]:
x_data * x_data.T

tensor([[ 1,  6],
        [ 6, 16]])

In [29]:
x_data.sum().item()

10

In [30]:
x_ones.add_(1)

tensor([[2, 2],
        [2, 2]])

In [31]:
x_ones

tensor([[2, 2],
        [2, 2]])